### PR TITLE
Prepare for upcoming Zonky changes

### PR DESCRIPTION
**Pull request by triceo**
Zonky will soon roll out the following changes:

- Max loan term goes up to 10 years.
- Max loan amount goes up to 900k.

I am making the necessary changes. I was not able to find any references to the original 700k amount, but I believe I changed all the term stuff.

Nice clean code, was easy to modify! Please point out if I skipped anything.

### CODE REVIEW

**Review by jhrcek — APPROVED** [review]
Looks good. Although the amount of places where this had to be changed was alarming, so I extracted it to constants. And also bumped robozonky version in integration tests and confirmed everything is still passing with robozonky master.

**Comment by jhrcek** [comment]
@triceo Let me know when you want this deployed and I'll create a PR to robozonky.github.io

**Comment by triceo** [comment]
@jhrcek Please create the PR and I'll merge it when I need to.
I expect to be releasing 6.3.3 later today.

**Comment by jhrcek** [comment]
Done. And regarding

> I was not able to find any references to the original 700k amount

The tool doesn't enforce any max limit there. Should it or is it ok as is?
Screenshot from 2021-02-28 10-50-17

**Comment by triceo** [comment]
I think it would be reasonable to have some limit there. Since there is no way how the amount would ever exceed 900k, let's set that as the limit.

That said, I will not be adding a limit to the strategy itself.

**Comment by jhrcek** [comment]
Of course, I'll add it later

**Pull request merged**
